---
- name: Deploy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /opt/mediaserver/docker-compose.yml
    owner: vagrant
    group: vagrant
    mode: "0644"

- name: Pull all images
  community.docker.docker_compose_v2_pull:
    project_src: /opt/mediaserver

- name: Start media stack
  community.docker.docker_compose_v2:
    project_src: /opt/mediaserver
    state: present
